version: '3.8'

services:
  container:
    image: spring-batch/spring-batch-metis-poc-transformation:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      JDK_JAVA_OPTIONS: -Xms500m -Xmx500m
#      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
    command: ["java", "-jar", "/app.jar",
              "datasetId=1",
              "executionId=233",
              "targetJob=TRANSFORMATION",
              "executionUUID=26",
              "datasetName=idA_metisDatasetNameA",
              "datasetCountry=Greece",
              "datasetLanguage=el",
              "xsltUrl=https://metis-core-rest.test.eanadev.org/datasets/xslt/6204e5e2514e773e6745f7e9"]
    memswap_limit: -1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1500M
        reservations:
          cpus: '2'
          memory: 1500M
    volumes:
#      - /data/metis-configuration/k8s/common-components/custom-truststore-jks/custom-truststore.jks:/data/certificates/custom-truststore.jks
      - /data/spring-batch-metis-poc/batch-application.properties:/application.properties
#      - /data/metis-configuration/k8s/common-components/log4j2-xml/log4j2.xml:/data/logging/log4j2.xml
