apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: postgresql
data:
  database-username: dXNlcm5hbWU=  # base64-encoded value of "username"
  database-password: cGFzc3dvcmQ=  # base64-encoded value of "password"