apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pg-hba-config
data:
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File
    # "local" is for Unix domain socket connections only
    local   all             all                                     peer
  
    # IPv4 local connections:
    host    all             all             127.0.0.1/32            md5
  
    # IPv6 local connections:
    host    all             all             ::1/128                 md5
  
    # Allow connections from all IP addresses using md5 authentication
    host    all             all             0.0.0.0/0               md5