apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        # Update accordingly
        url: jdbc:postgresql://host.minikube.internal:5432/dataflow
        username: admin
        password: admin
        driverClassName: org.postgresql.Driver
        
        