apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
                    imagePullPolicy: Always
      datasource:
        # Update accordingly
        url: <POSTGRES_JDBC_URL>
        username: admin
        password: <PASSWORD> 
        driverClassName: org.postgresql.Driver
        
