apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        # Get minikube ip and update
        url: jdbc:postgresql://postgresql.ecloud-spring-cdf-poc.svc.cluster.local:5432/dataflow
        username: username
        password: password
        driverClassName: org.postgresql.Driver
        
        